# permissions for end users to view featurestargets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: flipt-features-operator
    app.kubernetes.io/managed-by: kustomize
  name: featurestarget-viewer-role
rules:
- apiGroups:
  - flipt.nev.dev
  resources:
  - featurestargets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - flipt.nev.dev
  resources:
  - featurestargets/status
  verbs:
  - get
