---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - flipt.nev.dev
  resources:
  - features
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - flipt.nev.dev
  resources:
  - features/finalizers
  verbs:
  - update
- apiGroups:
  - flipt.nev.dev
  resources:
  - features/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - flipt.nev.dev
  resources:
  - featurestargets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - flipt.nev.dev
  resources:
  - featurestargets/finalizers
  verbs:
  - update
- apiGroups:
  - flipt.nev.dev
  resources:
  - featurestargets/status
  verbs:
  - get
  - patch
  - update
